version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - docs


  docs: 
    image: matrixorigin/matrixorigin.io:latest
    ports:
      - 8000
    restart: on-failure
    tty: true
    hostname: docs
