spring:
  profiles:
    #choose your env
    active: test
  application:
    name: codebot
  datasource:
    url: jdbc:mysql://${codebot.mo.ip}:${codebot.mo.port}/${codebot.mo.db}?characterSetResults=UTF-8&continueBatchOnError=false&useServerPrepStmts=true&alwaysSendSetIsolation=false&useLocalSessionState=true&zeroDateTimeBehavior=CONVERT_TO_NULL&failoverReadOnly=false&serverTimezone=Asia/Shanghai&socketTimeout=30000
    username: ${codebot.mo.username}
    password: ${codebot.mo.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis host
    host: ${codebot.redis.host}
    # Redis Server port
    port: ${codebot.redis.port}
    database: 0
    timeout: 1800000
    password: ${codebot.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true

jwt:
  secret: ${codebot.jwt.secret}

github:
  client:
    id: "Ov23liuwsvlUImneTgL2"
    authorize-url: "https://github.com/login/oauth/authorize"
    secret: "6ce0aee0a72f61263d941ffd6a5dcec35b243df0"
    redirect-url: "http://localhost:8080/oauth2/callback&state="
    access-token-url: "https://github.com/login/oauth/access_token"
    user-info-url: "https://api.github.com/user"
